name: POC3 Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/poc3-gar-pipeline.yaml
      - poc3-action-hub/**
  pull_request:
    paths:
      - .github/workflows/poc3-gar-pipeline.yaml
      - poc3-action-hub/**
  workflow_dispatch:

env:
  PROJECT_ID: looker-hackathon-2023
  GAR_LOCATION: us-central1
  GCE_ZONE: us-central1-a
  REPOSITORY: poc3-action-hub
  IMAGE: main

jobs:
  gar-login-build-push:
    name: GAR Login, Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Google Auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: '${{ env.PROJECT_ID }}'

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: 'Docker Build'
        working-directory: poc3-action-hub
        run: |-
          docker build . --file Dockerfile --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"
          docker build . --file Dockerfile --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest"

      - name: 'Docker Push to GAR'
        run: |-
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest"

      - name: 'Update the GCE instance'
        run: |-
          gcloud compute instances update-container looker-py-poc3 --project="${{ env.PROJECT_ID }}" --zone="${{ env.GCE_ZONE }}" --container-image="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"
